version: 2.1

jobs:
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          command: yarn
          name: Install dependencies
      - run:
          command: yarn run test
          name: Run YARN tests
  secure:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          command: yarn audit
          name: Verify dependencies
workflows:
  test_app:
    jobs:
      - test
