version: 2.1

jobs:
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          command: yarn
          name: Install dependencies
      - run:
          command: yarn run test
          name: Run YARN tests
  lint:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          command: yarn run lint
          name: "Check the lint"
          
workflows:
  test_app:
    jobs:
      - test
      - lint

